// Datos seed estáticos — se usan como respaldo cuando la GraphQL API
// (Microsoft Fabric SQL Database) no está conectada o falla. Las formas son
// idénticas a las que devuelve la API, incluidos los campos snake_case.

import type {
  Embarque,
  Incidencia,
  LoteEtiquetado,
  Pedido,
  PedidoLinea,
  PedidoSurtido,
  Recepcion,
  RegistroProductividad,
} from '@/types/cedis'

export const embarquesSeed: Embarque[] = [
  {
    id: 'emb-1',
    folio: 'EMB-24081',
    destino: 'CD Culiacán',
    transportista: 'Castores',
    unidades: 1840,
    hora_salida: '09:15',
    estado: 'transito',
    created_at: '2026-08-19T14:00:00Z',
    updated_at: '2026-08-19T15:15:00Z',
  },
  {
    id: 'emb-2',
    folio: 'EMB-24082',
    destino: 'CD Veracruz',
    transportista: 'Tresguerras',
    unidades: 960,
    hora_salida: null,
    estado: 'cargando',
    created_at: '2026-08-19T13:30:00Z',
    updated_at: null,
  },
  {
    id: 'emb-3',
    folio: 'EMB-24079',
    destino: 'CEDIS Monterrey',
    transportista: 'Castores',
    unidades: 2210,
    hora_salida: '07:40',
    estado: 'retrasado',
    created_at: '2026-08-18T13:00:00Z',
    updated_at: '2026-08-19T11:00:00Z',
  },
  {
    id: 'emb-4',
    folio: 'EMB-24076',
    destino: 'CD Guadalajara',
    transportista: 'Tresguerras',
    unidades: 1320,
    hora_salida: '09:40',
    estado: 'entregado',
    created_at: '2026-08-17T15:00:00Z',
    updated_at: '2026-08-18T17:00:00Z',
  },
  {
    id: 'emb-5',
    folio: 'EMB-24083',
    destino: 'CEDIS Puebla',
    transportista: 'Paquetexpress',
    unidades: 540,
    hora_salida: null,
    estado: 'programado',
    created_at: '2026-08-19T16:00:00Z',
    updated_at: null,
  },
]

export const recepcionesSeed: Recepcion[] = [
  {
    id: 'rec-1',
    folio: 'REC-19045',
    proveedor: 'Flourish Thrive Ddevelopments Taiwan Branch',
    anden: 'R-02',
    unidades: 3040,
    tipo: 'Abarrotes',
    estado: 'discrepancia',
    created_at: '2026-08-19T12:00:00Z',
    updated_at: '2026-08-19T13:20:00Z',
  },
  {
    id: 'rec-2',
    folio: 'REC-19046',
    proveedor: 'Great Ascent Trading',
    anden: 'R-05',
    unidades: 1500,
    tipo: 'Higiene',
    estado: 'inspeccion',
    created_at: '2026-08-19T15:00:00Z',
    updated_at: null,
  },
  {
    id: 'rec-3',
    folio: 'REC-19040',
    proveedor: 'Nice Elite International',
    anden: 'R-01',
    unidades: 2800,
    tipo: 'Abarrotes',
    estado: 'recibida',
    created_at: '2026-08-18T14:00:00Z',
    updated_at: '2026-08-18T15:10:00Z',
  },
  {
    id: 'rec-4',
    folio: 'REC-19048',
    proveedor: 'Profit Sign International',
    anden: 'R-03',
    unidades: 900,
    tipo: 'Textil',
    estado: 'descarga',
    created_at: '2026-08-19T17:00:00Z',
    updated_at: null,
  },
  {
    id: 'rec-5',
    folio: 'REC-19050',
    proveedor: 'Flourish Thrive Ddevelopments Taiwan Branch',
    anden: null,
    unidades: 1150,
    tipo: 'Electrónica',
    estado: 'programada',
    created_at: '2026-08-19T21:30:00Z',
    updated_at: null,
  },
]

// srt-1 y srt-4 nacen de un pedido capturado (`pedido_id`): son los dos casos
// que permiten recorrer el vínculo en los dos sentidos sin API. Su `cliente` y
// su conteo de `lineas` se dejaron iguales a los del pedido a propósito —con
// datos contradictorios la vista de detalle no se puede leer. Los otros tres
// van con `pedido_id: null`, que es el alta manual desde el propio módulo.
export const pedidosSurtidoSeed: PedidoSurtido[] = [
  {
    id: 'srt-1',
    pedido: 'PED-77210',
    cliente: 'Soriana',
    lineas: 4,
    operador: 'Fernando Uribe',
    prioridad: 'Alta',
    estado: 'surtiendo',
    pedido_id: 'ped-1',
    created_at: '2026-09-01T12:00:00Z',
    updated_at: '2026-09-02T14:30:00Z',
  },
  {
    id: 'srt-2',
    pedido: 'PED-77198',
    cliente: 'Price Shoes',
    lineas: 64,
    operador: 'Paola Camacho',
    prioridad: 'Media',
    estado: 'verificado',
    pedido_id: null,
    created_at: '2026-08-19T02:00:00Z',
    updated_at: '2026-08-19T13:00:00Z',
  },
  {
    id: 'srt-3',
    pedido: 'PED-77225',
    cliente: 'Innova Sports',
    lineas: 38,
    operador: null,
    prioridad: 'Baja',
    estado: 'pendiente',
    pedido_id: null,
    created_at: '2026-08-19T13:30:00Z',
    updated_at: null,
  },
  {
    id: 'srt-4',
    pedido: 'PED-77180',
    cliente: 'Chedraui',
    lineas: 3,
    operador: 'Paola Camacho',
    prioridad: 'Media',
    estado: 'completado',
    pedido_id: 'ped-2',
    created_at: '2026-08-28T14:00:00Z',
    updated_at: '2026-09-01T22:00:00Z',
  },
  {
    id: 'srt-5',
    pedido: 'PED-77230',
    cliente: 'Palacio de Hierro',
    lineas: 51,
    operador: 'Fernando Uribe',
    prioridad: 'Alta',
    estado: 'pausado',
    pedido_id: null,
    created_at: '2026-08-19T14:15:00Z',
    updated_at: '2026-08-19T16:05:00Z',
  },
]

// ---------------------------------------------------------------------------
// Pedidos del ERP
// ---------------------------------------------------------------------------
//
// Las fechas son fijas, como en el resto del seed. Eso significa que la métrica
// de "vencidos" envejece: `ped-4` está diseñado para caer vencido y los otros
// no, pero conforme pase el tiempo los demás también lo harán. Es un límite del
// respaldo estático, no un cálculo mal hecho — con la API conectada las fechas
// llegan vivas.
export const pedidosSeed: Pedido[] = [
  {
    id: 'ped-1',
    folio: 'PD-90114',
    cliente: 'Soriana',
    fecha_pedido: '2026-09-01T09:30:00Z',
    fecha_requerida: '2026-09-06T18:00:00Z',
    direccion_entrega: 'CEDIS Soriana Tlalnepantla, Av. Sor Juana Inés de la Cruz 280, Edo. Méx.',
    estado: 'asignado',
    notas: 'Entregar en andén 4. Cita confirmada por el proveedor logístico.',
    created_at: '2026-09-01T09:30:00Z',
    updated_at: '2026-09-01T12:00:00Z',
  },
  {
    id: 'ped-2',
    folio: 'PD-90108',
    cliente: 'Chedraui',
    fecha_pedido: '2026-08-28T11:00:00Z',
    fecha_requerida: '2026-09-02T17:00:00Z',
    direccion_entrega: 'CEDIS Chedraui Xalapa, Carr. Xalapa-Veracruz km 3.5, Ver.',
    estado: 'completado',
    notas: null,
    created_at: '2026-08-28T11:00:00Z',
    updated_at: '2026-09-01T22:00:00Z',
  },
  {
    id: 'ped-3',
    folio: 'PD-90121',
    cliente: 'Walmart',
    fecha_pedido: '2026-09-02T08:15:00Z',
    fecha_requerida: '2026-09-08T16:00:00Z',
    direccion_entrega: 'CEDIS Walmart Cuautitlán, Av. Central 45, Edo. Méx.',
    estado: 'pendiente',
    notas: 'Tarima estándar 1.20 × 1.00; rechazan estiba mixta.',
    created_at: '2026-09-02T08:15:00Z',
    updated_at: '2026-09-02T08:15:00Z',
  },
  {
    id: 'ped-4',
    folio: 'PD-90123',
    cliente: 'OXXO',
    fecha_pedido: '2026-08-30T14:40:00Z',
    fecha_requerida: '2026-09-02T12:00:00Z',
    direccion_entrega: 'CEDIS OXXO Ecatepec, Av. Central s/n, Edo. Méx.',
    estado: 'pendiente',
    notas: 'Pedido vencido: reprogramar cita con el cliente antes de surtir.',
    created_at: '2026-08-30T14:40:00Z',
    updated_at: '2026-08-30T14:40:00Z',
  },
  {
    id: 'ped-5',
    folio: 'PD-90126',
    cliente: 'Farmacias del Ahorro',
    fecha_pedido: '2026-09-03T10:05:00Z',
    fecha_requerida: '2026-09-10T15:00:00Z',
    direccion_entrega: null,
    estado: 'pendiente',
    notas: null,
    created_at: '2026-09-03T10:05:00Z',
    updated_at: '2026-09-03T10:05:00Z',
  },
]

/**
 * Renglones de los pedidos, con `linea` numerada 1..n **por pedido**: así llega
 * el consecutivo del ERP y así se muestra. El arreglo se deja agrupado por
 * pedido y en orden de línea para que el respaldo seed reproduzca el
 * `orderBy: { linea: ASC }` de la API sin ordenar nada en el cliente.
 */
export const pedidoLineasSeed: PedidoLinea[] = [
  // ped-1 · Soriana — en surtido, parcialmente cubierto
  {
    id: 'pl-1-1',
    pedido_id: 'ped-1',
    linea: 1,
    sku: 'ABA-10442',
    producto: 'Aceite comestible 850 ml',
    cantidad_solicitada: 480,
    cantidad_surtida: 480,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-1-2',
    pedido_id: 'ped-1',
    linea: 2,
    sku: 'ABA-10877',
    producto: 'Frijol bayo 1 kg',
    cantidad_solicitada: 360,
    cantidad_surtida: 200,
    unidad_medida: 'PZA',
    notas: 'Faltante parcial en zona B',
  },
  {
    id: 'pl-1-3',
    pedido_id: 'ped-1',
    linea: 3,
    sku: 'ABA-11250',
    producto: 'Azúcar estándar 2 kg',
    cantidad_solicitada: 240,
    cantidad_surtida: 240,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-1-4',
    pedido_id: 'ped-1',
    linea: 4,
    sku: 'HIG-20310',
    producto: 'Papel higiénico 4 rollos',
    cantidad_solicitada: 600,
    cantidad_surtida: 0,
    unidad_medida: 'PAQ',
    notas: null,
  },

  // ped-2 · Chedraui — completado
  {
    id: 'pl-2-1',
    pedido_id: 'ped-2',
    linea: 1,
    sku: 'ABA-10442',
    producto: 'Aceite comestible 850 ml',
    cantidad_solicitada: 300,
    cantidad_surtida: 300,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-2-2',
    pedido_id: 'ped-2',
    linea: 2,
    sku: 'ABA-13005',
    producto: 'Café soluble 200 g',
    cantidad_solicitada: 180,
    cantidad_surtida: 180,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-2-3',
    pedido_id: 'ped-2',
    linea: 3,
    sku: 'ABA-12118',
    producto: 'Galleta surtida 1 kg',
    cantidad_solicitada: 240,
    cantidad_surtida: 240,
    unidad_medida: 'CAJ',
    notas: null,
  },

  // ped-3 · Walmart — pendiente
  {
    id: 'pl-3-1',
    pedido_id: 'ped-3',
    linea: 1,
    sku: 'HIG-20455',
    producto: 'Detergente en polvo 5 kg',
    cantidad_solicitada: 400,
    cantidad_surtida: 0,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-3-2',
    pedido_id: 'ped-3',
    linea: 2,
    sku: 'HIG-20780',
    producto: 'Jabón de tocador 150 g',
    cantidad_solicitada: 960,
    cantidad_surtida: 0,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-3-3',
    pedido_id: 'ped-3',
    linea: 3,
    sku: 'ABA-10877',
    producto: 'Frijol bayo 1 kg',
    cantidad_solicitada: 520,
    cantidad_surtida: 0,
    unidad_medida: 'PZA',
    notas: null,
  },

  // ped-4 · OXXO — pendiente y vencido
  {
    id: 'pl-4-1',
    pedido_id: 'ped-4',
    linea: 1,
    sku: 'BEB-30112',
    producto: 'Agua natural 600 ml',
    cantidad_solicitada: 1200,
    cantidad_surtida: 0,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-4-2',
    pedido_id: 'ped-4',
    linea: 2,
    sku: 'BOT-31004',
    producto: 'Botana de maíz 45 g',
    cantidad_solicitada: 1800,
    cantidad_surtida: 0,
    unidad_medida: 'PZA',
    notas: 'Cuidar fecha de caducidad más próxima',
  },

  // ped-5 · Farmacias del Ahorro — pendiente
  {
    id: 'pl-5-1',
    pedido_id: 'ped-5',
    linea: 1,
    sku: 'HIG-20990',
    producto: 'Gel antibacterial 1 L',
    cantidad_solicitada: 300,
    cantidad_surtida: 0,
    unidad_medida: 'PZA',
    notas: null,
  },
  {
    id: 'pl-5-2',
    pedido_id: 'ped-5',
    linea: 2,
    sku: 'HIG-21044',
    producto: 'Toalla húmeda 80 pzas',
    cantidad_solicitada: 450,
    cantidad_surtida: 0,
    unidad_medida: 'PAQ',
    notas: null,
  },
  {
    id: 'pl-5-3',
    pedido_id: 'ped-5',
    linea: 3,
    sku: null,
    producto: 'Vitamina C 1 g, 10 tabletas',
    cantidad_solicitada: 220,
    cantidad_surtida: 0,
    unidad_medida: 'CAJ',
    notas: 'SKU pendiente de alta en el catálogo',
  },
]

export const lotesEtiquetadoSeed: LoteEtiquetado[] = [
  {
    id: 'etq-1',
    lote: 'LOT-33012',
    producto: 'Detergente 5 kg',
    unidades: 800,
    operador: 'Rosa Elena Tapia',
    estado: 'proceso',
    motivo_rechazo: null,
    created_at: '2026-08-19T15:00:00Z',
    updated_at: null,
  },
  {
    id: 'etq-2',
    lote: 'LOT-33009',
    producto: 'Tenis running mod. 220',
    unidades: 420,
    operador: 'Iván Rocha',
    estado: 'rechazado',
    motivo_rechazo: 'Código de barras ilegible en el 12% del lote',
    created_at: '2026-08-19T13:45:00Z',
    updated_at: '2026-08-19T14:10:00Z',
  },
  {
    id: 'etq-3',
    lote: 'LOT-33015',
    producto: 'Playera algodón talla M',
    unidades: 1100,
    operador: 'Rosa Elena Tapia',
    estado: 'etiquetado',
    motivo_rechazo: null,
    created_at: '2026-08-19T12:30:00Z',
    updated_at: '2026-08-19T16:00:00Z',
  },
  {
    id: 'etq-4',
    lote: 'LOT-33018',
    producto: 'Galleta surtida 1 kg',
    unidades: 260,
    operador: null,
    estado: 'pendiente',
    motivo_rechazo: null,
    created_at: '2026-08-19T18:00:00Z',
    updated_at: null,
  },
  {
    id: 'etq-5',
    lote: 'LOT-33005',
    producto: 'Bota industrial dieléctrica',
    unidades: 940,
    operador: 'Rosa Elena Tapia',
    estado: 'etiquetado',
    motivo_rechazo: null,
    created_at: '2026-08-18T21:00:00Z',
    updated_at: '2026-08-18T23:30:00Z',
  },
]

export const incidenciasSeed: Incidencia[] = [
  {
    id: 'inc-1',
    folio: 'INC-5510',
    tipo: 'discrepancia_inventario',
    severidad: 'alta',
    estado: 'abierta',
    modulo: 'recepciones',
    descripcion: 'Faltante de 160 unidades en recepción REC-19045',
    responsable: 'Karla Solís',
    fechaCreacion: '2026-08-19T07:25:00-06:00',
  },
  {
    id: 'inc-2',
    folio: 'INC-5508',
    tipo: 'etiquetado_rechazado',
    severidad: 'media',
    estado: 'atencion',
    modulo: 'etiquetado',
    descripcion: 'Lote LOT-33009 rechazado por código de barras ilegible',
    responsable: 'Iván Rocha',
    fechaCreacion: '2026-08-19T07:50:00-06:00',
  },
  {
    id: 'inc-3',
    folio: 'INC-5512',
    tipo: 'retraso_transporte',
    severidad: 'critica',
    estado: 'abierta',
    modulo: 'embarques',
    descripcion: 'Embarque EMB-24079 con más de 24h de retraso hacia Monterrey',
    responsable: 'Jorge Nava',
    fechaCreacion: '2026-08-19T05:10:00-06:00',
  },
  {
    id: 'inc-4',
    folio: 'INC-5501',
    tipo: 'falla_equipo',
    severidad: 'media',
    estado: 'resuelta',
    modulo: 'surtido',
    descripcion: 'Montacargas MC-04 fuera de servicio en Zona B',
    responsable: 'Fernando Uribe',
    fechaCreacion: '2026-08-18T11:00:00-06:00',
    fechaResolucion: '2026-08-18T13:30:00-06:00',
  },
  {
    id: 'inc-5',
    folio: 'INC-5495',
    tipo: 'dano_mercancia',
    severidad: 'baja',
    estado: 'cerrada',
    modulo: 'recepciones',
    descripcion: 'Tarima con 8 cajas dañadas en recepción de abarrotes',
    responsable: 'Diego Ríos',
    fechaCreacion: '2026-08-17T10:00:00-06:00',
    fechaResolucion: '2026-08-17T16:00:00-06:00',
  },
  {
    id: 'inc-6',
    folio: 'INC-5513',
    tipo: 'error_surtido',
    severidad: 'baja',
    estado: 'atencion',
    modulo: 'surtido',
    descripcion: 'Diferencia de 6 piezas en pedido PED-77210',
    responsable: 'Paola Camacho',
    fechaCreacion: '2026-08-19T10:05:00-06:00',
  },
]

export const registrosProductividadSeed: RegistroProductividad[] = [
  {
    id: 'prod-1',
    operador: 'Fernando Uribe',
    area: 'Surtido',
    turno: 'matutino',
    unidades: 2496,
    horas: 8,
    meta: 2720,
    created_at: '2026-08-19T14:00:00Z',
  },
  {
    id: 'prod-2',
    operador: 'Karla Solís',
    area: 'Recepciones',
    turno: 'matutino',
    unidades: 3720,
    horas: 8,
    meta: 3360,
    created_at: '2026-08-19T14:00:00Z',
  },
  {
    id: 'prod-3',
    operador: 'Rosa Elena Tapia',
    area: 'Etiquetado',
    turno: 'vespertino',
    unidades: 2016,
    horas: 7,
    meta: 2100,
    created_at: '2026-08-18T22:00:00Z',
  },
  {
    id: 'prod-4',
    operador: 'Marisol Peña',
    area: 'Embarques',
    turno: 'vespertino',
    unidades: 1584,
    horas: 8,
    meta: 1760,
    created_at: '2026-08-18T22:00:00Z',
  },
  {
    id: 'prod-5',
    operador: 'Paola Camacho',
    area: 'Surtido',
    turno: 'nocturno',
    unidades: 2200,
    horas: 8,
    meta: 2400,
    created_at: '2026-08-17T06:00:00Z',
  },
]
